\newlabel{All the noise}
\newlabel{DiffusionAnalysis}
\newlabel{Organisation of the data structure}
\newlabel{Reformatting the data to the offline structure}
\newlabel{eq:HitTime}
\newlabel{fig:AngleCanvas}
\newlabel{fig:CDiff4DataFit}
\newlabel{fig:CoherentNoise}
\newlabel{fig:CounterCoincidence}
\newlabel{fig:CounterDiffFreq}
\newlabel{fig:CounterTrackAngle}
\newlabel{fig:DataCollected}
\newlabel{fig:DataDrops}
\newlabel{fig:DataRecoEffics}
\newlabel{fig:DataStructure}
\newlabel{fig:DiffDataAvDiff}
\newlabel{fig:DiffDataFit}
\newlabel{fig:DiffDataHitFit}
\newlabel{fig:DiffDataPredHit}
\newlabel{fig:DiffLotsOfFlashes}
\newlabel{fig:DiffMCHitFit}
\newlabel{fig:DistanceCanvas}
\newlabel{fig:DomDiffSchem}
\newlabel{fig:DomsHitModel}
\newlabel{fig:FreqCollection}
\newlabel{fig:FreqFFT}
\newlabel{fig:FreqInduction}
\newlabel{fig:FreqWaveform}
\newlabel{fig:FrequencyFilter}
\newlabel{fig:NoiseRemoval}
\newlabel{fig:StuckCodes}
\newlabel{fig:TingjunLifetime}
\newlabel{fig:TwoDimCanvas}
\newlabel{sec:DataAlgs}
\newlabel{sec:DiffMCStudies}
\newlabel{sub@fig:AngleCanvas}
\newlabel{sub@fig:CDiff4DataFit}
\newlabel{sub@fig:CounterDiffFreq}
\newlabel{sub@fig:DistanceCanvas}
\newlabel{sub@fig:FreqCollection}
\newlabel{sub@fig:FreqFFT}
\newlabel{sub@fig:FreqInduction}
\newlabel{sub@fig:FreqWaveform}
\newlabel{sub@fig:TwoDimCanvas}
