\newlabel{fig:Minnion}
\newlabel{fig:TomJerry}
\newlabel{fig:WallE}
\newlabel{fig:animations}
\newlabel{fig:minion}
\newlabel{section1.3}
\newlabel{sub@fig:Minnion}
\newlabel{sub@fig:TomJerry}
\newlabel{sub@fig:WallE}
\newlabel{table:bad_table}
\newlabel{table:good_table}
\newlabel{table:nice_table}
