\newlabel{Organisation of the data structure}
\newlabel{Reformatting the data to the offline structure}
\newlabel{chap:35tonData}
\newlabel{eq:SigCol}
\newlabel{eq:SigInd}
\newlabel{fig:AngleCanvas}
\newlabel{fig:CDiff4DataFit}
\newlabel{fig:CoherentNoise}
\newlabel{fig:CounterCoincidence}
\newlabel{fig:CounterDiffFreq}
\newlabel{fig:CounterTrackAngle_EW}
\newlabel{fig:CounterTrackAngle_NS}
\newlabel{fig:CounterTrackAngle}
\newlabel{fig:DataCollected}
\newlabel{fig:DataDrops}
\newlabel{fig:DataRecoEffics}
\newlabel{fig:DataStructure}
\newlabel{fig:DiffDataAvDiff_RMS_Int_T}
\newlabel{fig:DiffDataAvDiff_RMS_Int_X}
\newlabel{fig:DiffDataAvDiff_RMS_Int}
\newlabel{fig:DiffDataAvDiff_RMS_T}
\newlabel{fig:DiffDataAvDiff_RMS_X}
\newlabel{fig:DiffDataAvDiff_RMS}
\newlabel{fig:DiffDataHitFit_RMSQ20}
\newlabel{fig:DiffDataHitFit}
\newlabel{fig:DiffDataPredHit}
\newlabel{fig:DiffData_AngFit}
\newlabel{fig:DiffData_ChargeCut}
\newlabel{fig:DiffElecStudy_AvDiffRMS_T}
\newlabel{fig:DiffElecStudy_AvDiffRMS_X}
\newlabel{fig:DiffElecStudy_AvDiff_RMS_Int_T}
\newlabel{fig:DiffElecStudy_AvDiff_RMS_Int_X}
\newlabel{fig:DiffElecStudy_AvDiff_RMS_Int}
\newlabel{fig:DiffElecStudy_AvDiff_RMS}
\newlabel{fig:DiffLDiff_AvDiffRMS_T}
\newlabel{fig:DiffLDiff_AvDiffRMS_X}
\newlabel{fig:DiffLDiff_AvDiff_RMS_Int_T}
\newlabel{fig:DiffLDiff_AvDiff_RMS_Int_X}
\newlabel{fig:DiffLDiff_AvDiff_RMS_Int}
\newlabel{fig:DiffLDiff_AvDiff_RMS}
\newlabel{fig:DiffLifeStudy_AvDiffRMS_T}
\newlabel{fig:DiffLifeStudy_AvDiffRMS_X}
\newlabel{fig:DiffLifeStudy_AvDiff_RMS_Int_T}
\newlabel{fig:DiffLifeStudy_AvDiff_RMS_Int_X}
\newlabel{fig:DiffLifeStudy_AvDiff_RMS_Int}
\newlabel{fig:DiffLifeStudy_AvDiff_RMS}
\newlabel{fig:DiffLotsOfFlashes}
\newlabel{fig:DiffMCDataCompFit}
\newlabel{fig:DiffMCDataCompInt}
\newlabel{fig:DiffMCHitFit_3}
\newlabel{fig:DiffMCHitFit}
\newlabel{fig:DiffNoiseStudy_AvDiffRMS_T}
\newlabel{fig:DiffNoiseStudy_AvDiffRMS_X}
\newlabel{fig:DiffNoiseStudy_AvDiff_RMS_Int_T}
\newlabel{fig:DiffNoiseStudy_AvDiff_RMS_Int_X}
\newlabel{fig:DiffNoiseStudy_AvDiff_RMS_Int}
\newlabel{fig:DiffNoiseStudy_AvDiff_RMS}
\newlabel{fig:DiffOverlayAvDiff_RMS_Int_T}
\newlabel{fig:DiffOverlayAvDiff_RMS_Int_X}
\newlabel{fig:DiffOverlayAvDiff_RMS_Int}
\newlabel{fig:DiffOverlayAvDiff_RMS_T}
\newlabel{fig:DiffOverlayAvDiff_RMS_X}
\newlabel{fig:DiffOverlayAvDiff_RMS}
\newlabel{fig:DiffOverlay_ChargeCut}
\newlabel{fig:DistanceCanvas}
\newlabel{fig:DomDiffSchem}
\newlabel{fig:DomsHitModel}
\newlabel{fig:EWCounters}
\newlabel{fig:FreqCollection}
\newlabel{fig:FreqFFT}
\newlabel{fig:FreqInduction}
\newlabel{fig:FreqWaveform}
\newlabel{fig:FrequencyFilter}
\newlabel{fig:NoiseRemoval_Mit}
\newlabel{fig:NoiseRemoval_Raw}
\newlabel{fig:NoiseRemoval}
\newlabel{fig:StuckCodes}
\newlabel{fig:TingjunLifetime}
\newlabel{fig:TwoDimCanvas}
\newlabel{sec:AllTheNoise}
\newlabel{sec:DataAlgs}
\newlabel{sec:DiffLimitations}
\newlabel{sec:DiffMCStudies}
\newlabel{sec:DiffusionAnalysis}
\newlabel{sec:MCDataComp}
\newlabel{sub@fig:AngleCanvas}
\newlabel{sub@fig:CounterDiffFreq}
\newlabel{sub@fig:CounterTrackAngle_EW}
\newlabel{sub@fig:CounterTrackAngle_NS}
\newlabel{sub@fig:DiffDataAvDiff_RMS_Int_T}
\newlabel{sub@fig:DiffDataAvDiff_RMS_Int_X}
\newlabel{sub@fig:DiffDataAvDiff_RMS_T}
\newlabel{sub@fig:DiffDataAvDiff_RMS_X}
\newlabel{sub@fig:DiffDataHitFit_RMSQ20}
\newlabel{sub@fig:DiffElecStudy_AvDiffRMS_T}
\newlabel{sub@fig:DiffElecStudy_AvDiffRMS_X}
\newlabel{sub@fig:DiffElecStudy_AvDiff_RMS_Int_T}
\newlabel{sub@fig:DiffElecStudy_AvDiff_RMS_Int_X}
\newlabel{sub@fig:DiffLDiff_AvDiffRMS_T}
\newlabel{sub@fig:DiffLDiff_AvDiffRMS_X}
\newlabel{sub@fig:DiffLDiff_AvDiff_RMS_Int_T}
\newlabel{sub@fig:DiffLDiff_AvDiff_RMS_Int_X}
\newlabel{sub@fig:DiffLifeStudy_AvDiffRMS_T}
\newlabel{sub@fig:DiffLifeStudy_AvDiffRMS_X}
\newlabel{sub@fig:DiffLifeStudy_AvDiff_RMS_Int_T}
\newlabel{sub@fig:DiffLifeStudy_AvDiff_RMS_Int_X}
\newlabel{sub@fig:DiffMCHitFit_3}
\newlabel{sub@fig:DiffNoiseStudy_AvDiffRMS_T}
\newlabel{sub@fig:DiffNoiseStudy_AvDiffRMS_X}
\newlabel{sub@fig:DiffNoiseStudy_AvDiff_RMS_Int_T}
\newlabel{sub@fig:DiffNoiseStudy_AvDiff_RMS_Int_X}
\newlabel{sub@fig:DiffOverlayAvDiff_RMS_Int_T}
\newlabel{sub@fig:DiffOverlayAvDiff_RMS_Int_X}
\newlabel{sub@fig:DiffOverlayAvDiff_RMS_T}
\newlabel{sub@fig:DiffOverlayAvDiff_RMS_X}
\newlabel{sub@fig:DistanceCanvas}
\newlabel{sub@fig:FreqCollection}
\newlabel{sub@fig:FreqFFT}
\newlabel{sub@fig:FreqInduction}
\newlabel{sub@fig:FreqWaveform}
\newlabel{sub@fig:NoiseRemoval_Mit}
\newlabel{sub@fig:NoiseRemoval_Raw}
\newlabel{sub@fig:TwoDimCanvas}
\newlabel{tab:CDiffAng}
